### PR TITLE
Changed Style to Avenir Next

### PR DESCRIPTION
**Pull request by YashBit**
button - font-weight: bold ;

### CODE REVIEW

**Comment by AkankshaBodhankar** [comment]
Code looks good!

**Comment by AkankshaBodhankar** [comment]
post the screenshot in the gci task and the link to PR. Resolve the merge conflicts and make a PR you are good to go with the task.

**Comment by YashBit** [comment]
I have uploaded the screenshot but I don't know how to solve the merge issue .Could you teach me please.

**Comment by AkankshaBodhankar** [comment]
Simply refork the project and make PR again don't worry it's simple. Just take backup of changes. Delete this fork
Refork
Same procedure to upload your chnaged code again :-) Good work ! After this you are good to go won't take much time :-)

**Comment by YashBit** [comment]
https://github.com/systers/FirstAide-web/pull/41
I did it again , please accept it . :) Haha .
Thanks for sticking with me for so long .

**Pull request closed without merging**
