### PR TITLE
Alert texts added

### PR DESCRIPTION
**Pull request by Raxerz**
Fixes issue #172

### CODE REVIEW

**Comment by AkankshaBodhankar** [comment]
Post the screenshots.

**Comment by Raxerz** [comment]
Here are the screenshots @AkankshaBodhankar 

screenshot from 2017-03-15 22 37 48

screenshot from 2017-03-15 22 38 13

screenshot from 2017-03-15 22 38 25

**Comment by AkankshaBodhankar** [comment]
Can you change the messages to something more appropriate? Like must be a valid username and Example: ABCD123
Also, put a little gap between the line and text.

**Comment by Raxerz** [comment]
Yes. That sounds better. 
Will make the modifications @AkankshaBodhankar .

**Pull request closed without merging**
