### PR TITLE
Fixes #157 : Added reCaptcha setup documentation

### LINKED ISSUE #157: Documentation for setting up reCaptcha credentials
In settings.php, the user needs to enter his/her google reCaptcha credentials to make it work on the localhost. Documentation needs to be updated to explain the same.

### LINKED ISSUE #166: Readme file getting too large, Switch to Distributed documentation
Due to a large number of enhancements and additions in the project documentation the Readme file has become quite large. We can have a distributed documentation, where we can include contribution guidlines, Database setup etc in different files. @AkankshaBodhankar 

Something like this systers repository: https://github.com/systers/macc

### PR DESCRIPTION
**Pull request by fatimarafiqui**
Fixes #157 Added reCaptcha setup documentation to the existing README.md file. Also corrected minor spacing issues in few headings according to markdown file standards.

@AkankshaBodhankar I feel the README.md file has become even more large after this. We should try to fix #166  after this. What do you say?

### CODE REVIEW

**Comment by AkankshaBodhankar** [comment]
Yes. The readme file is becoming too large I would like to wait until Gsoc for changing it as it involves lot of changes.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar I have already made the PR in the README itself for now. For now it is important to merge it for new users who might join in. Whenever you give me a headstart to work on #166 I will modify the structure. But for now, I feel this should me merged to avoid confusion.

**Comment by AkankshaBodhankar** [comment]
Put links to images rather than images.

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui Resolve the merge conflicts

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar I will try to do it ASAP. Something urgent has come up at college.

**Pull request closed without merging**
