### PR TITLE
Corrected spelling in menu.php

### PR DESCRIPTION
**Pull request by swapsha96**
Issue no. #72

### CODE REVIEW

**Comment by swapsha96** [comment]
This is a major concern which needs to be addressed in issue #77

**Comment by AkankshaBodhankar** [comment]
@swapsha96 I really appreciate the work you have done. But, I cannot be unfair to the other contributors. These issues have been created by other contributors. The spelling mistake was created by someone else in #72  and the issue you have created for encryption was already created here #48.
Please go through the rules of contributing before starting to contribute. See this: https://github.com/systers/FirstAide-web#rules-for-contributing 
The issue is generally assigned to the person who created it.

**Comment by swapsha96** [comment]
@AkankshaBodhankar I completely respect rules for contributing but that no one has not created PR in last 2 and 4 days respectively and I did it within few hours. I apologise for my behaviour but I NEED this for GSoC '17. I'll stay in queue and keep working on other issues. Thank you.

**Comment by AkankshaBodhankar** [comment]
That's okay. It always takes time before someone responds. It's better you
stick to the rules.

**Pull request closed without merging**
