### PR TITLE
Fixes #91: Added Stay signed in option on login page

### LINKED ISSUE #91: Stay Signed In option on Sign In page.
@AkankshaBodhankar Can we give such option like Stay Signed In to user whether wants to keep logged in untill he/she logout or allow him to logout after some time automatically? If it is then Can i start my work for this?

### PR DESCRIPTION
**Pull request by Dhara159**
User can choose to be logged in for 1 hour by selecting stay signed in option

### CODE REVIEW

**Comment by npari** [comment]
@Dhara159 Can you submit a Gif showing this feature, along with this PR? How does the user know that he/she is still logged in?

**Comment by Dhara159** [comment]
sure

**Comment by Dhara159** [comment]
final

**Comment by AkankshaBodhankar** [comment]
Looks good to merge from my side. @npari Is this good to go from your side as well?

**Pull request merged**
