### PR TITLE
country code updates for circle of trust

### PR DESCRIPTION
**Pull request by sudhachauhan**
with squashed commits

### CODE REVIEW

**Comment by AkankshaBodhankar** [comment]
Can you remove the automatic + sign. we will add it at the backend. Also, because right now we are in development phase we will need all the countries. Sorry for the huge changes after you have made a PR.

**Comment by sudhachauhan** [comment]
oh sure, I'll wait.

**Comment by AkankshaBodhankar** [comment]
@sudhachauhan #11 has the list of countries can you add them as well and resolve the merge conflicts so we can merge this PR.

**Comment by MehaKaushik** [comment]
@sudhachauhan can you please resolve the conflicts ? Please let us know, in case you are no longer interested in working on this PR. Thank you for your hard work.

**Comment by MehaKaushik** [comment]
Due to no response from the author and multiple conflicts, I am closing this PR.

**Pull request closed without merging**
