### PR TITLE
Fixes #163: Resolved the problem of refilling the data on registration page when duplicate email validation failes

### LINKED ISSUE #163: User has to refill all the details if error occurs on registration page
@AkankshaBodhankar When user tries to register the form and during registration if any error occurs, user has to refill all the form detail again. So, can we do such thing like user has to fill only that detail where validation was failed. and other detail would be same as filled up.

### PR DESCRIPTION
**Pull request by Dhara159**
User don't has to refill all the data except email-id on registration page if the duplicate email has been entered and validation failes

### CODE REVIEW

**Comment by AkankshaBodhankar** [comment]
@Dhara159 Can you post a gif showing the working of this? Also, make sure you do post a gif whenever you make a PR.

**Comment by Dhara159** [comment]
Okay. I will make sure.

fa97ed2a-4284-11e7-899d-6495eeef8090

**Comment by fatimarafiqui** [comment]
@Dhara159 Are you sure this branch is upto date with develop? I think we just have one button 'Create Account' on the signup page. Correct me if I am wrong.

**Comment by Dhara159** [comment]
okay.

**Comment by AkankshaBodhankar** [comment]
@Dhara159 Resolve the conflicts.

**Comment by fatimarafiqui** [comment]
@Dhara159 Please rebase your code to the current master.

**Comment by Dhara159** [comment]
Okay. I got the problem. I will solve it as soon as possible.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar @Dhara159 This has been taken care of in https://github.com/systers/FirstAide-web/pull/232. We can close it.

**Comment by Dhara159** [comment]
do I need to update the code or it will do?

**Comment by fatimarafiqui** [comment]
No @Dhara159, I dont think you need to update anything now. Let's for Akanksha's affirmative.

**Comment by MehaKaushik** [comment]
@Dhara159 Thank you for raising this up. I would be closing this now, since it is covered by @fatimarafiqui in PR 232.

**Pull request closed without merging**
