### PR TITLE
Fixes #91: Added Stay signed in option on login page

### LINKED ISSUE #91: Stay Signed In option on Sign In page.
@AkankshaBodhankar Can we give such option like Stay Signed In to user whether wants to keep logged in untill he/she logout or allow him to logout after some time automatically? If it is then Can i start my work for this?

### PR DESCRIPTION
**Pull request by Dhara159**

### CODE REVIEW

**Comment by Dhara159** [comment]
1.) SS of the registration.php
screenshot 175

**Comment by Dhara159** [comment]
1.)Screenshot of login.php
screenshot 178

**Comment by AkankshaBodhankar** [comment]
Can you show the working?

**Comment by Dhara159** [comment]
Yes. Sure.

**Comment by Dhara159** [comment]
is this okay @AkankshaBodhankar ?

**Comment by AkankshaBodhankar** [comment]
Looks good.

**Comment by AkankshaBodhankar** [comment]
Can you reopen this PR?

**Comment by Dhara159** [comment]
@AkankshaBodhankar Actually, the option of reopening PR is disabled and it is showing **The repository that submitted this pull request has been deleted**. So, is that okay if I create new PR for this issue?

**Comment by AkankshaBodhankar** [comment]
Sure.

**Comment by MehaKaushik** [comment]
@Dhara159 which one is the new PR for this ?

**Comment by Dhara159** [comment]
#227 is the id of the new PR for this problem.

**Pull request closed without merging**
