### PR TITLE
Added icons (Call and message) to all the dialogs

### PR DESCRIPTION
**Pull request by pandilladivya**
I've added icons to all the dialogs..

image

Kindly review

@MeepyMay , @rosariorobinson , @AkankshaBodhankar 

Thank You!

### CODE REVIEW

**Comment by pandilladivya** [comment]
@AkankshaBodhankar 
Is this PR good to go or are there any changes to be made?
Kindly Review

Thank You :)

**Comment by pandilladivya** [comment]
@AkankshaBodhankar 
Any updates on this?!

**Comment by pandilladivya** [comment]
@AkankshaBodhankar 

What are the changes do I need to make?
You didn't mention it anywhere.

Thank You :)

**Comment by AkankshaBodhankar** [comment]
See the comments section in the changes. In one of the file one line space
is extra.

**Comment by AkankshaBodhankar** [comment]
I have added a note.

**Comment by AkankshaBodhankar** [comment]
minor change which can be ignored for now.

**Pull request merged**
