### PR TITLE
Fixes #177: Added loader during long response time

### LINKED ISSUE #177: Add loader during long response time
This issue is specially for the calling and sms. when user press the button for calling or message, it takes three or four seconds to response Specially on **Circle of trust** page. There is no such loader. On **Get help now** we can see that page is loading by watching on the left side of the tab header. So, can we use such loader to show that his/her response is getting submited?

### PR DESCRIPTION
**Pull request by Dhara159**
Resolved issue #177 : Added loader during long response time in getHelpNow and circleOfTrust page when user submit request for calling and sending sms.

### CODE REVIEW

**Comment by fatimarafiqui** [comment]
@Dhara159 Please upload a gif here as well.

**Comment by Dhara159** [comment]
Here is the gif:
radio1

**Comment by AkankshaBodhankar** [comment]
Looks good to go. @MehaKaushik @npari Are there any changes which you would like to suggest?

**Comment by MehaKaushik** [comment]
Looks great. The gif and the code changes, both are good to go. We can merge this.

**Pull request merged**
