### PR TITLE
Fixes #119 : stored twilio credentials in a file

### LINKED ISSUE #119: Store Twilio credentials in a separate file
Currently twillio credentials are stored in three different files: twilioSMS.php, twilioCall.php and groupsms.php.
We should store the credentials in a separate file due to following reasons:

1. It is cumbersome to copy paste and maintain the credentials at three different locations.
2. Someone can by mistake commit his/her credentials in the PR, thus we can maintain the file in gitignore file to make the system more secure and intact.
3. In future, if the credentials or the token needs to be changed it can be changed at a single location and it would reflect instantly.
4. Overall it would increase security, flexibility to change and reduce chances of human error.

### PR DESCRIPTION
**Pull request by fatimarafiqui**
Fixes #119 : Stored twilio credentials in a single file and also tested the working.

screen shot 2017-03-24 at 01 15 45

### CODE REVIEW

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar Any updates on this?

**Comment by npari** [comment]
@fatimarafiqui Currently mentors are busy with GSoC17 reviews which is our priority at the moment. Thanks for submitting the Pull Request, we will get back to you once we find time.

**Comment by fatimarafiqui** [comment]
@npari sure, not a problem at all.

**Comment by AkankshaBodhankar** [comment]
Looks good :-)

**Pull request merged**
