### PR TITLE
Fixes #63 : Added country list dropdown 

### LINKED ISSUE #63: Add check for country field
There is no check for value accepted in the country field on the signup page. It is accepting any value, as shown in the screenshot.

screen shot 2017-02-07 at 23 45 51

screen shot 2017-02-07 at 23 46 19

I would suggest we can use a dropdown that enlists all the countries. @AkankshaBodhankar

### PR DESCRIPTION
**Pull request by fatimarafiqui**
Fixing #63 
Added a list of all countries. Also moved the session check to the top as initialising session (session_start)  anywhere except the first line was throwing a warning as shown below.

screen shot 2017-03-05 at 12 38 43
error of session

### CODE REVIEW

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar Please review this.

**Comment by AkankshaBodhankar** [comment]
why have you added the session start? Please make PR only for the country code list dropdown only

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar I have not added session_start. I have just placed the session code that you wrote at the beginning of the page. Its just a rearrangement to avoid the unnecessary warning of session cache limiter due to session start at the end. I have also posted a screenshot for the same warning above.

If you still suggest of undoing it, I will do it. But the warning will come up again.

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui Try using jquery for adding a dropdown of countries instead of adding all the countries in the option tag

**Pull request closed without merging**
