### PR TITLE
Fixes #177: Added loader during long response time

### LINKED ISSUE #117: Refactor circleOfTrustMessage.js
In circleOfTrustMessage.js the same code is written multiple times. We can instead parameterise it and avoid the redundancy. 
This would minify the code to enhance the page load speed and improvise it for the better, specially for countries like Uganda, where we have slower internet connectivity.

refactor

### LINKED ISSUE #177: Add loader during long response time
This issue is specially for the calling and sms. when user press the button for calling or message, it takes three or four seconds to response Specially on **Circle of trust** page. There is no such loader. On **Get help now** we can see that page is loading by watching on the left side of the tab header. So, can we use such loader to show that his/her response is getting submited?

### PR DESCRIPTION
**Pull request by Dhara159**
Resolved issue #177 :  Added loader during long response time in getHelpNow and circleOfTrust page when user submit request for calling and sending sms.

### CODE REVIEW

**Comment by AkankshaBodhankar** [comment]
Post screenshots.

**Comment by Dhara159** [comment]
1.)Calling:
screenshot 216
screenshot 217
screenshot 218

2.) Sending SMS:
screenshot 219
screenshot 220
screenshot 221

**Comment by AkankshaBodhankar** [comment]
@Dhara159 Can you try a different loader?

**Comment by Dhara159** [comment]
Yes, sure. I will. Is there any specific requirement @AkankshaBodhankar?

**Comment by Dhara159** [comment]
Hello @AkankshaBodhankar,
I have changed the loader gif. Here is the screenshot of the new loader gif.
The loader which i had uploaded earlier was also a gif.
frame_5_delay-0 03s
frame_8_delay-0 03s
frame_11_delay-0 03s
frame_14_delay-0 03s
frame_17_delay-0 03s

**Comment by AkankshaBodhankar** [comment]
Can you add a simple loader instead? Also, resolve the conflicts

**Comment by Dhara159** [comment]
Ok, @AkankshaBodhankar.

**Comment by fatimarafiqui** [comment]
@Dhara159 Kindly resolve the merge conflicts  and make the pending changes. Cheers!

**Comment by Dhara159** [comment]
Sure. I will do this as soon as possible.

**Comment by Dhara159** [comment]
@AkankshaBodhankar @fatimarafiqui I have replaced the old one with the simple loader as per fatimarafiqui said. I have chosen the color of the loader based on the theme of the application.
Here is the loader gif:
radio1
.

**Comment by fatimarafiqui** [comment]
@Dhara159 This looks really nice! Can you post a screenshot of how this loader will look when applied to the application? I mean how it would come out with the application background.

**Comment by fatimarafiqui** [comment]
@Dhara159 This loader looks really nice! Can you reduce the size of the loader and reduce its opacity to 0.6, I feel that would look more subtle. Also, Can you please record and post a gif to illustrate the working? You can use http://www.cockos.com/licecap/

**Comment by Dhara159** [comment]
Okay. Here is the gif with updated opacity of 0.6
loader

**Comment by fatimarafiqui** [comment]
@Dhara159 Awesome!

**Comment by fatimarafiqui** [comment]
@Dhara159 Please send a new PR having all the correct changes as suggested above, with the new loader keeping the Opacity as 0.6. You had not pushed the complete code with the changes in this PR.

**Comment by Dhara159** [comment]
Sorry for the mistake. I will create a new PR for this issue.

**Comment by Dhara159** [comment]
I have created new PR and the id is #229

**Pull request merged**
