### PR TITLE
Adding UML diagrams

### PR DESCRIPTION
**Pull request by fatimarafiqui**
Adding UML diagrams for the complete web application.
Task:  https://trello.com/c/qzeG1LTJ

### CODE REVIEW

**Comment by prathmeshranaut** [comment]
These look good for me. Waiting for a review from @MehaKaushik and @AkankshaBodhankar before merging.

**Comment by MehaKaushik** [comment]
Why is home.jpg pushed here? @fatimarafiqui

**Comment by MehaKaushik** [comment]
Some comments:
1. I am not sure of the significance of home.jpg file here. Can you explain me @fatimarafiqui ?
2. Please add architectural design also.

**Comment by npari** [comment]
@fatimarafiqui can you add what story/bug this PR is for and link the trello task here?

**Comment by fatimarafiqui** [comment]
@npari Sure. Here it is https://trello.com/c/qzeG1LTJ

**Comment by AkankshaBodhankar** [comment]
@fatimarafiqui As @MehaKaushik mentioned already the home.png doesn't seem relevant here? Have you added it by mistake?

**Comment by AkankshaBodhankar** [comment]
Also, it would be nice if you can create a pdf and then make PR for adding it under project-docs folder.

**Comment by fatimarafiqui** [comment]
@AkankshaBodhankar @MehaKaushik I thought while adding diagrams on the wiki page, It would be good to add a screenshot of the home. Also, I think we should keep it on hold because in the present directory structure we do not have any project doc folder.

**Comment by MehaKaushik** [comment]
I am closing this PR. We would add the project docs in the directory folder in new structure.

**Pull request closed without merging**
