### PR TITLE
logged in as name in next line

### PR DESCRIPTION
**Pull request by shreyans29**
solved issue #108

### CODE REVIEW

**Comment by shreyans29** [comment]
name next line

**Comment by AkankshaBodhankar** [comment]
Looks fine what happens when you type a long name. Can you post a screenshot for that as well?

**Comment by AkankshaBodhankar** [comment]
screenshot 981

**Comment by AkankshaBodhankar** [comment]
It still overflows just putting it in the next line is not resolving the issue. Think of another solution for it

**Pull request merged**
